In [2]:
import tensorflow as tf
import cv2
import random
import numpy as np
import tensorflow_triplet_loss.model.triplet_loss as triplet_loss

In [3]:
mode = 'gait_recognition'
date = '2022_6_20_15_22'
model = tf.keras.models.load_model(f'/home/aaron/Desktop/Aaron/College-level_Applied_Research/gait_log/{mode}/{date}/GaitNet/trained_ckpt')

2022-06-20 15:31:18.009520: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-20 15:31:18.009648: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-20 15:31:18.024559: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-20 15:31:18.024657: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-20 15:31:18.024718: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from S

In [17]:
file_names = [str(random.randint(1, 10308)).zfill(5) for i in range(64)]
image_list = np.zeros((64, 128, 88, 3))

for i, name in enumerate(file_names):
    img = cv2.imread(f'/home/aaron/Desktop/Aaron/College-level_Applied_Research/GEI/090-00/{name}.png')
    image_list[i] = img

[ WARN:0@1855.403] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/aaron/Desktop/Aaron/College-level_Applied_Research/GEI/090-00/01761.png'): can't open/read file: check file path/integrity
[ WARN:0@1855.403] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/aaron/Desktop/Aaron/College-level_Applied_Research/GEI/090-00/07906.png'): can't open/read file: check file path/integrity


In [28]:
file_names[-2] = file_names[-1]
file_names[1] = file_names[2]  

In [29]:
embeddings = model(image_list)

In [30]:
embeddings.numpy()

array([[ 1., -1.,  1., ...,  1., -1.,  1.],
       [ 1., -1.,  1., ...,  1., -1.,  1.],
       [ 1., -1.,  1., ...,  1., -1.,  1.],
       ...,
       [ 1., -1.,  1., ...,  1., -1.,  1.],
       [ 1., -1.,  1., ...,  1., -1.,  1.],
       [ 1., -1.,  1., ...,  1., -1.,  1.]], dtype=float32)

In [31]:
triplet_loss.batch_all_triplet_loss(np.array(file_names).astype(np.float32), embeddings.numpy(), margin=0.001)

(<tf.Tensor: shape=(), dtype=float32, numpy=nan>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.43145162>)

In [7]:
np.array(file_names).shape

(64,)

In [10]:
np.array(file_names).astype(np.float32)

array([ 7518.,  6921.,  4489.,  2738.,  8189.,  5140.,  1092.,  6532.,
        2241.,  9946.,  7513.,  2770.,  5829.,  6840.,  5658.,  8426.,
        8305.,  9317.,  6977.,  9011., 10038.,  5145.,  2402.,  4836.,
        6805.,  8886.,  3505.,  6810.,  8289.,  7720.,  9241.,  3118.,
        9318.,  1971.,  9034.,  3930.,  2132.,  1759.,  5395.,  5646.,
        5242.,  9240.,  3081.,  5875.,  2328.,   986.,  9459.,  9725.,
        5005.,  2139.,  2598.,  2566.,  4144.,  1070.,  6342.,  7334.,
       10154.,  5996.,  8096.,   348.,  9629.,  6553.,  6376.,  3352.],
      dtype=float32)